title = "Silicon"
gitRepoUrl = "https://github.com/PolyVectors/Silicon"

[home]
enabled = true
includeReadme = true

[[home.features]]
title = "⚡ Blazingly Fast"
description = "Singletons are designed to be simple tables of functions and events, focused on being lightweight with speed as a consequence, inspired by Knit."

[[home.features]]
title = "🛠️ Minimal Boilerplate"
description = "Create services and controllers with minimal boilerplate, inspired by Flamework."

[[home.features]]
title = "🤔 Simple Design"
description = "Designed to be simple by abstracting complex concepts (e.g. Networking, Services) while maintaining simple syntax, inspired by Fusion."

[navbar]
title = ""

[navbar.logo]
src = "/logo.png"
alt = "Silicon"

[docusaurus]
favicon = "/favicon.png"
tagline = "A Fusion, Flamework and Knit inspired modern game framework created for use in Roblox"

[footer]
style = "dark"
copyright = "Copyright © 2023 PolyVector. Built with Moonwave and Docusaurus"