[package]
name = "poly/silicon"
description = "A Fusion, Flamework, and Knit inspired modern game framework designed for use in Roblox."
license = "MIT"
authors = ["PolyVector"]
version = "0.1.0-alpha.6"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"