[package]
name = "polyvectors/silicon"
description = "A Fusion, Flamework, and Knit inspired modern game framework designed for use in Roblox."
license = "MIT"
authors = ["PolyVector"]
version = "0.1.0-alpha.8"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
promise = "evaera/promise@4.0.0"