[package]
name = "polyvectors/silicon"
description = "A Fusion, Flamework, and Knit inspired modern game framework designed for use in Roblox."
license = "MIT"
authors = ["PolyVector"]
version = "0.2.0-beta.5"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src"]

[dependencies]
promise = "evaera/promise@4.0.0"
