[package]
name = "poly/silicon"
version = "0.1.0-alpha.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
promise = "evaera/promise@4.0.0"
option = "grilme99/option@1.0.5"